/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 cleaning.gltf --transform
Author: Sousinho (https://sketchfab.com/sousinho)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/caution-wet-floor-cleaning-sign-v2-272133d56b1742fa91b2f52ad5405313
Title: caution wet floor / cleaning sign v2
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/cleaning-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<mesh
						geometry={nodes.defaultMaterial.geometry}
						material={materials.T_caustion_sign_closed_1001}
						position={[-0.01, 1.14, 1.48]}
						rotation={[-1.55, 0, 0]}
						scale={100}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/cleaning-transformed.glb");
