/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 piggy_bank.gltf --transform
Author: octopuslover (https://sketchfab.com/octopuslover)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/piggy-bank-4d5bf8d42f2d4c3493dc13a168944d64
Title: Piggy Bank
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/piggy_bank-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]}>
					<group position={[-0.37, 0, 0]}>
						<mesh
							geometry={nodes.Object_5.geometry}
							material={materials.pigskin}
							position={[0.37, 0, 0]}
						/>
					</group>
					<mesh
						geometry={nodes.Object_7.geometry}
						material={materials.Black}
						position={[1.7, 0.99, -0.54]}
						rotation={[-0.65, -0.03, 0.46]}
						scale={[0.08, 0.11, 0.09]}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("/piggy_bank-transformed.glb");
